### ISSUE TITLE
Apollo could not be run with sourced.ml@develp branch

### ISSUE THREAD

**Issue by bzz** [src-d/apollo#18]
Right now, if one

```
git clone https://github.com/src-d/apollo.git; cd apollo
virtualenv -p python3 .venv-py3
source .venv-py3/bin/activate

pip install git+https://github.com/src-d/ml.git@develop
pip3 install -e .
```

and then `apollo --help` it will result in

```
$ apollo --help
Traceback (most recent call last):
  File "./src-d/apollo/.venv-py3/bin/apollo", line 11, in <module>
    load_entry_point('apollo', 'console_scripts', 'apollo')()
  File "./src-d/apollo/.venv-py3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "./src-d/apollo/.venv-py3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "./src-d/apollo/.venv-py3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "./src-d/apollo/.venv-py3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "./src-d/apollo/apollo/__main__.py", line 12, in <module>
    from apollo.bags import preprocess_source, source2bags
  File "./src-d/apollo/apollo/bags.py", line 8, in <module>
    from sourced.ml.transformers import UastExtractor, Transformer, Cacher, UastDeserializer, Engine, \
ImportError: cannot import name 'Documents2BOW'
```

From https://github.com/src-d/ml/pull/160/files#diff-9bdc53996c12b1f5ff9117bb4bf0ae23R7 it seems that `Repo2WeightedSet` was renamed in sourced.ml, but https://github.com/src-d/apollo/blob/5faf5a5bcb2d27968853eaee4534da599c2f458a/apollo/bags.py#L9 still uses it.

**Comment by zurk** [comment]
Fixed. @vmarkovtsev need to review them and as soon as these two PRs are merged, you are free to use new versions of sourced ml and Apollo.

**Comment by bzz** [comment]
Thank you so much for fast fixes @zurk !

@vmarkovtsev excited to try it out as soon as all of them got merged! 

BTW, would you consider cutting a new https://github.com/src-d/apollo/releases with those fixes as well?

**Comment by vmarkovtsev** [comment]
We got stuck on repairing CI, once we fix it, will be done.

**Comment by bzz** [comment]
Thank you so much @vmarkovtsev for keeping us posted! 🤞 for CI

**Comment by vmarkovtsev** [comment]
@zurk Would you kindly add `sourced-ml` to `requirements.txt` and `setup.py` and check if this problem persists.

**Comment by zurk** [comment]
Fixed. Tested on ubuntu 16.04
To solve issue need to be merged:
- PR https://github.com/src-d/ml/pull/186
- PR https://github.com/src-d/apollo/pull/28

@bzz, after that, you can try:
```
git clone https://github.com/src-d/apollo.git; cd apollo
virtualenv -p python3 .venv-py3
source .venv-py3/bin/activate

pip install git+https://github.com/src-d/ml.git
pip3 install -e .
apollo --help
```
If @vmarkovtsev publish a new `souced-ml` to pypi, no need to run `pip install git+https://github.com/src-d/ml.git`.

It gives help message.
Right now I am checking that apollo subcommands work as expected.

**Comment by zurk** [comment]
It should work fine now and we can close it
@vmarkovtsev @bzz
