### ISSUE TITLE
apollo urls command is still present in the readme

### ISSUE THREAD

**Issue by carlosms** [src-d/apollo#36]
The readme contains instructions for `apollo urls`, but apparently that command was removed here https://github.com/src-d/apollo/commit/df3fbd807be2bef441fcb2636467b30747524d11
I'm not submitting a PR because I'm not sure if the command must be removed, or replaced with something else.

**Comment by vmarkovtsev** [comment]
Good to notice, fixed by https://github.com/src-d/apollo/commit/7880a9be29c391047442efe86c804c926e7f6967
